name: ideal
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '^2.18.0'

dependencies:
  flutter:
    sdk: flutter
  states_rebuilder:
  hive_flutter:
  freezed_annotation:
  json_annotation: 
  uuid:
  file_picker: ^5.2.5
  google_fonts:
  colornames:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  freezed:
  json_serializable:
  lints:
  very_good_analysis:

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/fonts/
